OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"
          - "0.0.0.0"

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    Template:
      Count: 2
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.example.com
    Template:
      Count: 2
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1
  - Name: Org3
    Domain: org3.example.com
    Template:
      Count: 2
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org4
    Domain: org4.example.com
    Template:
      Count: 2
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1

  - Name: Org5
    Domain: org5.example.com
    Template:
      Count: 2
      SANS:
        - "localhost"
        - "127.0.0.1"
        - "0.0.0.0"
    Users:
      Count: 1